baseURL: "https://ghenry.co.uk/"
title: "Gavin Henry's Blog"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-475334-16
disqusShortname: ghenry

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Gavin Henry's Blog"
  description: "Gavin Henry's Blog about all things tech"
  keywords: [Blog, Portfolio, PaperMod]
  author: Gavin Henry
  # author: ["Me", "You"] # multiple authors
  images: ["https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowFullTextinRSS: true # Supports to show your whole contents in RSS, not just summary
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"
    favicon16x16: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"
    favicon32x32: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"
    apple_touch_icon: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"
    safari_pinned_tab: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Gavin Henry's Blog"
    subtitle: "All things tech"
    imageUrl: "https://pbs.twimg.com/profile_images/1566092118086516736/CAbU48Qt_400x400.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Gavin Henry"
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Categories
        url: categories

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: I'm Gavin Henry and welcome to my blog.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ghenry"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/1072411/gavin-henry"
    - name: github
      url: "https://github.com/ghenry"
    - name: linkedin
      url: "https://www.linkedin.com/in/surevoip/"
    - name: rss # Shows an RSS feed icon on your site`
      url: "index.xml" # Your RSS feed url path

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/ghenry/blog/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalink:
  posts: /:year/:month/:day/:title/