baseURL = "https://ghenry.co.uk/"
languageCode = "en-gb"
title = "Gavin Henry"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Gavin Henry"
  description = "Gavin Henry's personal website."
  [params.footer]
    text = "By Gavin Henry"
    url = "https://github.com/ghenry"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

